"""empty message

Revision ID: 166c8ee1539e
Revises: df3bda4c82b2
Create Date: 2020-01-22 13:09:20.645078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166c8ee1539e'
down_revision = 'df3bda4c82b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('started', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'started')
    # ### end Alembic commands ###
