"""empty message

Revision ID: 489f0fff179f
Revises: 7474de89edf1
Create Date: 2020-01-03 03:04:10.537386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489f0fff179f'
down_revision = '7474de89edf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_binding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.String(length=512), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_binding')
    op.drop_table('role')
    # ### end Alembic commands ###
