"""empty message

Revision ID: 5aaf0990dfab
Revises: 489f0fff179f
Create Date: 2020-01-03 09:20:17.686694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aaf0990dfab'
down_revision = '489f0fff179f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('kind', sa.String(length=64), nullable=False))
    op.add_column('role', sa.Column('scope_kind', sa.String(length=64), nullable=False))
    op.add_column('role', sa.Column('scope_target', sa.Integer(), nullable=True))
    op.drop_constraint('role_org_id_fkey', 'role', type_='foreignkey')
    op.drop_column('role', 'org_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('role_org_id_fkey', 'role', 'organisation', ['org_id'], ['id'])
    op.drop_column('role', 'scope_target')
    op.drop_column('role', 'scope_kind')
    op.drop_column('role', 'kind')
    # ### end Alembic commands ###
