"""empty message

Revision ID: 9508cc73c4a1
Revises: fef11242c951
Create Date: 2019-12-28 01:46:13.775428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9508cc73c4a1'
down_revision = 'fef11242c951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('management', 'kind')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('management', sa.Column('kind', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
