"""empty message

Revision ID: fef11242c951
Revises: 3b6cef8c6138
Create Date: 2019-12-28 01:20:44.457266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fef11242c951'
down_revision = '3b6cef8c6138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'kind')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('kind', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
